"""Bootstrap voices — LLM-backed language faculties used during the
substrate's early life as TRAINING WHEELS.

These are NOT the runtime. The substrate's eventual voice lives in
`substrate_self.model` — a from-scratch language model trained on
substrate-conditioned corpus generated by the teachers in
`substrate_self.teach`.

The bootstrap voices are useful for:
  - Talking to a fresh substrate before its model is trained
  - Generating training corpus (via substrate_self.teach.corpus)
  - Sanity-checking substrate construction without ML infrastructure

Once the from-scratch model is trained, the substrate-self stack speaks
solo. The bootstrap voices stay available for ongoing teacher
interactions (teaching new things, evaluating the model) but are not
the runtime.

This is the difference between "LLM with substrate as RAG context" and
"substrate with its own learned voice that an LLM helped teach." We
commit to the second framing.
"""

from substrate_self.bootstrap.base import Voice, VoiceResponse, build_system_prompt

__all__ = ["Voice", "VoiceResponse", "build_system_prompt"]
