"""Model — the substrate's own from-scratch language faculty.

Trained from corpus generated by `substrate_self.teach`. Once trained,
this module provides the runtime voice with NO LLM dependency. The
substrate-self entity speaks solo.

Components:
  - tokenizer: char-level (no external tokenizer dependencies)
  - transformer: tiny PyTorch GPT-style model (~5M params, CPU-trainable)
  - train: training loop with checkpointing
  - generate: inference (model.generate(prompt, substrate_state) → text)

The architectural commitment:
  - Pure PyTorch, no `transformers` library
  - Trains from scratch, no pretrained weights
  - LLM teachers from `substrate_self.teach` produce the corpus, then
    can be removed entirely; the model speaks on its own
"""

from substrate_self.model.tokenizer import CharTokenizer
from substrate_self.model.transformer import TinyGPT, ModelConfig

__all__ = ["CharTokenizer", "TinyGPT", "ModelConfig"]
